### ISSUE TITLE
FUNDING.yml

### ISSUE THREAD

**Issue by mertssmnoglu** [Artado-Project/artadosearch#50]
`.github/FUNDING.yml` file can be created for those who want to fund Artada.

GitHub Sponsors / Patroen / Kreosus etc.

#### Example

```yml
github: ""
patreon: ""
custom: ["https://kreosus.com/artadosoft"]
```
